In [33]:
import numpy as np

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros((3, 4), dtype=int)


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Заповнює масив значеннями з [0..1)
np.random.random((4, 2))

array([[0.16911084, 0.08833981],
       [0.68535982, 0.95339335],
       [0.00394827, 0.51219226],
       [0.81262096, 0.61252607]])

In [ ]:
# Такий же як random
np.random.seed(10)
np.random.uniform(size=(4, 2))

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071]])

In [42]:
np.random.seed(10)
np.random.uniform(0, 10, size=(4, 2))

array([[7.71320643, 0.20751949],
       [6.33648235, 7.48803883],
       [4.98507012, 2.24796646],
       [1.98062865, 7.60530712]])

In [39]:
# Псевдо-випадкові числа
np.random.seed(10)
np.random.random((4, 2))


array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071]])

In [ ]:
np.random.randint(10, 20, size=(2, 4))

array([[10, 18, 16, 14],
       [13, 10, 14, 16]])

In [60]:
np.random.choice(np.array([1, 2, 3, 4, 5, 6]), size=10)

array([6, 6, 4, 2, 6, 5, 2, 5, 2, 2])