In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(15, 25)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [3]:
np.arange(10, 30, 3)

array([10, 13, 16, 19, 22, 25, 28])

In [5]:
np.arange(20).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
# Перетворення на "плаский" одномірний масив
np.random.randint(10, 20, size=(2, 3, 4)).flatten()


array([16, 18, 17, 18, 11, 16, 15, 19, 19, 19, 18, 15, 15, 10, 13, 16, 15,
       17, 15, 16, 11, 15, 17, 18])