In [1]:
import numpy as np
first = np.array([[1,2,3],[4,5,6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
# Форма массива та кількість елементів 2 на 3
first.shape

(2, 3)

In [3]:
# Розмірність (двумірний)
first.ndim

2

In [4]:
# Розмір масива
first.size

6

In [5]:
# Тип елементів
first.dtype

dtype('int64')

In [6]:
second = np.array([[7,8,9],[10,11,12]])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [8]:
first + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [9]:
first - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [10]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [11]:
first / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [12]:
# Елемент масива 1й ряд, 0 стовбчик
first[1,0]

np.int64(4)

In [13]:
# За змовчанням axis=0
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.concatenate((first, second), axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [15]:
np.concatenate((np.array([1,2,3]),(np.array([4,5,6]))))

array([1, 2, 3, 4, 5, 6])